on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - stable

name: "Deploy"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy
        run: ls ./packages/vscode-host/dist
