on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: "Deploy"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.23.6
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: pnpm
      - run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy
        run: ls ./packages/vscode-host/dist
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: |
            pr-{{PR_NUMBER}}.ethereum-viewer.vercel.app
